{{ if .Values.dhcp }}
{{ range $dhcp := .Values.dhcp.pops }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dhcp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    run: {{ include "dhcp.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 3300
    targetPort: 3300
    protocol: TCP
    name: dhcp
  selector:
    app: {{ include "dhcp.fullname" . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dhcp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    app: {{ include "dhcp.fullname" . }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ include "dhcp.fullname" . }}
  serviceName: "{{ include "dhcp.fullname" . }}-headless"
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
        app: {{ include "dhcp.fullname" . }}
    spec:
      {{- if .hostMode }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
      - name: dhcp
        {{- if .hostMode }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 8443
        - containerPort: 8086
        - containerPort: 5672
        - containerPort: 3300
        - containerPort: 8080
        - containerPort: 67
        - containerPort: 67
          protocol: UDP
        - containerPort: 5300
        {{- end }}
        image: {{ $.Values.dhcp.image.name }}:{{ $.Values.dhcp.image.tag }}
        imagePullPolicy: {{ $.Values.dhcp.image.pullPolicy }}
        env:
        - name: CONTAINER_NAME
          value: "dhcp"
        - name: CONFIG_PORT
          value: "3300"
        - name: NO_MIN_CHECK
          value: "true"
        command:
          - "/script/entry.sh"
        livenessProbe:
          exec:
            command:
            - supd
            - health
          initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
          failureThreshold: {{ .livenessProbe.failureThreshold }}
          periodSeconds: {{ .livenessProbe.periodSeconds }}
        resources:
{{ toYaml .resources | indent 10 }}
        volumeMounts:
        - mountPath: /ns1/data
          name: {{ include "dhcp.fullname" . }}
        - name: dhcp-entrypoint
          mountPath: /script/entry.sh
          subPath: entry.sh
      enableServiceLinks: false
      volumes:
      - name: dhcp-entrypoint
        configMap:
          name: {{ include "dhcp.fullname" . }}-entrypoint
          defaultMode: 0777
      imagePullSecrets:
      - name: {{ $.Values.imagePullSecret }}
    {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "dhcp.fullname" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "{{ .storage.className }}"
      resources:
        requests:
          storage: {{ .storage.size }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dhcp.fullname" . }}-entrypoint
  labels:
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
data:
  entry.sh: |
    #! /bin/sh
    /usr/local/bin/entrypoint \
        {{- range $flag := .startupFlags }}
        {{ $flag }} \
        {{- end }}
        --service_def_id={{ .serviceDefID }} \
        --pop_id={{ .popID }} \
        --server_id=$HOSTNAME \
        --core_host={{ .coreService }} \
        --enable_ops_metrics={{ .enableOpsMetrics }}
---
{{ end }}
{{ end }}
