{{ with .Values.core }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "core.fullname" . }}
                port:
                  number: 443
#    - https:
#        paths:
#          - path: /
#            backend:
#              service:
#                name: {{ include "core.fullname" . }}
#                port:
#                  number: 443
{{ end }}